language: python

sudo: false

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

before_install:
  - pip install -r test-requirements.txt
  - pip install codecov

install:
  - python setup.py install

script:
  - py.test --cov --cov-report=term-missing -vv

after_success:
  - codecov
